POST http://localhost:3001/api/guests HTTP/1.1
content-type: application/json

{
"guest": {
    "name": "Paco & Paki 5",
    "platform": "HomeEx",
    "password": 3,
    "dates": {
      "from": "2024-04-01T12:00",
      "to":"2024-04-10T23:00"
    }
  }
}